#!/usr/bin/python3
'''
Fenter - Format enters

Formatting string from \\n to one string.

Example:
```
Hello World, this very
long string.

Bue World!
```

To
```
Hello World, this very long string.

Bue World!
```
'''
import sys
import io


local_name_of_utility = __file__.split('/')[-1]


HELP = f"Usage:\n  {local_name_of_utility} file"


def to_format(data):
    return data.replace("\n", " ").replace("  ", "\n\n")


def main():
    if len(sys.argv) == 1:
        try:
            sys.stdin.tell()
            print(to_format(sys.stdin.read()))
        except io.UnsupportedOperation:
            print(HELP)
    else:
        for file_name in sys.argv[1:]:
            try:
                with open(file_name) as file:
                    print(to_format(file.read()))
                    if len(sys.argv)-1 != sys.argv.index(file_name):
                        print('\n\n')
            except FileNotFoundError:
                print(f"{local_name_of_utility}: {file_name}: No such file or directory")
                sys.exit(1)


if __name__ == '__main__':
    main()
